<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Revisao</RootNamespace>
    <AssemblyName>RevisaoB</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\comum\*.cs" />
    <Content Include="..\conteudo\conteudo-revisao.json"
             Link="conteudo-revisao.json"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
