# -*- coding: utf-8 -*-
"""
O ALGORITMO DO MURAL, EM PORTUGOL (VisuAlg) - a fonte de verdade.

Este arquivo e o unico lugar onde o Portugol dos passos esta escrito.
Quem consome:

    montar-conteudo.py  ->  conteudo/passos-mural.json
                        ->  folhas/gerar_folhas.py (a folha B impressa)
                        ->  projeto-desafio/ (o aplicativo)

Mudou uma linha aqui, muda no papel E na tela. Nao existe segunda copia.
"""

PASSOS = [
    dict(
        n=1,
        nome="O molde do recado",
        onde="Recado.cs - TODO 1",
        estreia="uma classe pode ser so um molde de dado: nao tem metodo nenhum",
        metodo=False,
        linhasEscrita=6,
        portugol=[
            "tipo Recado = registro",
            "   Id: inteiro",
            "   Autor: caractere",
            "   Texto: caractere",
            "   DataHora: data",
            "fimregistro",
        ]),

    dict(
        n=2,
        nome="Descrever",
        onde="frmMural.cs - TODO 2",
        estreia="funcao com parametro - devolve, e nao mexe na tela",
        metodo=True,
        linhasEscrita=9,
        portugol=[
            "funcao Descrever(r: Recado): caractere",
            "inicio",
            "   retorne \"[\" + formata(r.DataHora, \"dd/MM HH:mm\")",
            "           + \"] \" + r.Autor + \": \" + r.Texto",
            "fimfuncao",
            "",
            "// vira:  [25/08 20:14] Ana Souza: alguem tem a apostila?",
            "//",
            "// ARMADILHA: usar txtAutor aqui dentro em vez de usar",
            "// o r que chegou. Vai parecer que funcionou.",
        ]),

    dict(
        n=3,
        nome="CarregarMural",
        onde="frmMural.cs - TODO 3",
        estreia="procedimento que CONSOME o retorno de outros dois metodos",
        metodo=True,
        linhasEscrita=8,
        portugol=[
            "procedimento CarregarMural()",
            "var recados: vetor de Recado",
            "inicio",
            "   recados <- MuralDAO.Listar()",
            "",
            "   limpe(lstMural)",
            "",
            "   para cada r em recados faca",
            "      acrescente(lstMural, Descrever(r))",
            "   fimpara",
            "",
            "   lblSaudacao <- Saudacao(tamanho(recados))",
            "fimprocedimento",
            "",
            "// percorre o que EXISTE, sem precisar da posicao: foreach",
            "// depois de escrever, volte ao frmMural_Shown e CHAME ele",
        ]),

    dict(
        n=4,
        nome="Os campos, e o Gravar",
        onde="MuralDAO.cs - TODO 4",
        estreia="static: a lista tem de ser UMA SO para o programa inteiro",
        metodo=True,
        linhasEscrita=8,
        portugol=[
            "// no alto da classe MuralDAO, fora dos metodos:",
            "var recados: vetor de Recado",
            "    proximoId: inteiro <- 1",
            "",
            "funcao Gravar(r: Recado): inteiro",
            "inicio",
            "   r.Id <- proximoId",
            "   proximoId <- proximoId + 1",
            "   acrescente(recados, r)",
            "   retorne r.Id",
            "fimfuncao",
            "",
            "// quem chama pode ignorar o Id devolvido - e legitimo",
        ]),

    dict(
        n=5,
        nome="Listar",
        onde="MuralDAO.cs - TODO 5",
        estreia="devolve uma COLECAO - e o unico laco que precisa da posicao",
        metodo=True,
        linhasEscrita=8,
        portugol=[
            "funcao Listar(): vetor de Recado",
            "var mural: vetor de Recado",
            "    i: inteiro",
            "inicio",
            "   mural <- vetor vazio",
            "",
            "   para i de tamanho(recados) - 1 ate 0 passo -1 faca",
            "      acrescente(mural, recados[i])",
            "   fimpara",
            "",
            "   retorne mural",
            "fimfuncao",
            "",
            "// de tras para a frente: o mais NOVO e o ULTIMO que entrou",
            "// a ultima posicao e tamanho - 1, nunca tamanho",
        ]),

    dict(
        n=6,
        nome="Publicar  (evento)",
        onde="frmMural.cs - TODO 6",
        estreia="o unico metodo cuja assinatura voce NAO escolhe",
        metodo=True,
        linhasEscrita=6,
        portugol=[
            "procedimento btnPublicar_Click()",
            "var r: Recado",
            "inicio",
            "   se limpa(txtAutor) = \"\" entao",
            "      avise(\"Escreva o seu nome antes de publicar.\")",
            "      retorne",
            "   fimse",
            "   se limpa(txtTexto) = \"\" entao",
            "      avise(\"O recado esta vazio.\")",
            "      retorne",
            "   fimse",
            "   se comprimento(limpa(txtAutor)) < 3 entao",
            "      avise(\"O nome precisa ter pelo menos 3 letras.\")",
            "      retorne",
            "   fimse",
            "",
            "   r <- novo Recado",
            "   r.Autor <- limpa(txtAutor)",
            "   r.Texto <- limpa(txtTexto)",
            "   r.DataHora <- agora()",
            "",
            "   MuralDAO.Gravar(r)",
            "",
            "   Limpar()",
            "   CarregarMural()",
            "fimprocedimento",
        ]),

    dict(
        n=7,
        nome="Saudacao",
        onde="frmMural.cs - TODO 7",
        estreia="o retorno vira texto na tela - se ninguem pegar, some",
        metodo=True,
        linhasEscrita=8,
        portugol=[
            "funcao Saudacao(quantos: inteiro): caractere",
            "inicio",
            "   escolha quantos",
            "      caso 0",
            "         retorne \"Mural vazio - seja o primeiro a publicar.\"",
            "      caso 1",
            "         retorne \"1 recado no mural.\"",
            "      outrocaso",
            "         retorne quantos + \" recados no mural.\"",
            "   fimescolha",
            "fimfuncao",
            "",
            "// UM valor so contra constantes: e escolha, nao se",
        ]),

    dict(
        n=8,
        nome="Procurar",
        onde="frmMural.cs - TODO 8",
        estreia="o acumulador vira o retorno - contar nao e localizar",
        metodo=True,
        linhasEscrita=6,
        portugol=[
            "funcao Procurar(termo: caractere): inteiro",
            "var recados: vetor de Recado",
            "    quantos: inteiro",
            "inicio",
            "   recados <- MuralDAO.Listar()",
            "   quantos <- 0",
            "",
            "   limpe(lstMural)",
            "",
            "   para cada r em recados faca",
            "      se contem(minusculo(r.Texto), minusculo(termo)) entao",
            "         acrescente(lstMural, Descrever(r))",
            "         quantos <- quantos + 1",
            "      fimse",
            "   fimpara",
            "",
            "   retorne quantos",
            "fimfuncao",
        ]),

]
